// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package wrapping

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// EncryptedBlobInfo contains information about the encrypted value along with
// information about the key used to encrypt it
type EncryptedBlobInfo struct {
	// Ciphertext is the encrypted bytes
	Ciphertext []byte `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	// IV is the initialization value used during encryption
	IV []byte `protobuf:"bytes,2,opt,name=iv,proto3" json:"iv,omitempty"`
	// HMAC is the bytes of the HMAC, if any
	HMAC []byte `protobuf:"bytes,3,opt,name=hmac,proto3" json:"hmac,omitempty"`
	// Wrapped can be used by the client to indicate whether Ciphertext
	// actually contains wrapped data or not. This can be useful if you want to
	// reuse the same struct to pass data along before and after wrapping.
	Wrapped bool `protobuf:"varint,4,opt,name=wrapped,proto3" json:"wrapped,omitempty"`
	// KeyInfo contains information about the key that was used to create this value
	KeyInfo *WrappingKeyInfo `protobuf:"bytes,5,opt,name=key_info,json=keyInfo,proto3" json:"key_info,omitempty"`
	// ValuePath can be used by the client to store information about where the
	// value came from
	ValuePath            string   `protobuf:"bytes,6,opt,name=ValuePath,proto3" json:"ValuePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedBlobInfo) Reset()         { *m = EncryptedBlobInfo{} }
func (m *EncryptedBlobInfo) String() string { return proto.CompactTextString(m) }
func (*EncryptedBlobInfo) ProtoMessage()    {}
func (*EncryptedBlobInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *EncryptedBlobInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedBlobInfo.Unmarshal(m, b)
}
func (m *EncryptedBlobInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedBlobInfo.Marshal(b, m, deterministic)
}
func (m *EncryptedBlobInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedBlobInfo.Merge(m, src)
}
func (m *EncryptedBlobInfo) XXX_Size() int {
	return xxx_messageInfo_EncryptedBlobInfo.Size(m)
}
func (m *EncryptedBlobInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedBlobInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedBlobInfo proto.InternalMessageInfo

func (m *EncryptedBlobInfo) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

func (m *EncryptedBlobInfo) GetIV() []byte {
	if m != nil {
		return m.IV
	}
	return nil
}

func (m *EncryptedBlobInfo) GetHMAC() []byte {
	if m != nil {
		return m.HMAC
	}
	return nil
}

func (m *EncryptedBlobInfo) GetWrapped() bool {
	if m != nil {
		return m.Wrapped
	}
	return false
}

func (m *EncryptedBlobInfo) GetKeyInfo() *WrappingKeyInfo {
	if m != nil {
		return m.KeyInfo
	}
	return nil
}

func (m *EncryptedBlobInfo) GetValuePath() string {
	if m != nil {
		return m.ValuePath
	}
	return ""
}

// WrappingKeyInfo contains information regarding which Wrapper key was used to
// encrypt the entry
type WrappingKeyInfo struct {
	// Mechanism is the method used by the seal to encrypt and sign the
	// data as defined by the seal.
	Mechanism     uint64 `protobuf:"varint,1,opt,name=Mechanism,proto3" json:"Mechanism,omitempty"`
	HMACMechanism uint64 `protobuf:"varint,2,opt,name=HMACMechanism,proto3" json:"HMACMechanism,omitempty"`
	// This is an opaque ID used by the seal to identify the specific
	// key to use as defined by the seal.  This could be a version, key
	// label, or something else.
	KeyID     string `protobuf:"bytes,3,opt,name=KeyID,proto3" json:"KeyID,omitempty"`
	HMACKeyID string `protobuf:"bytes,4,opt,name=HMACKeyID,proto3" json:"HMACKeyID,omitempty"`
	// These value are used when generating our own data encryption keys
	// and encrypting them using the autoseal
	WrappedKey []byte `protobuf:"bytes,5,opt,name=WrappedKey,proto3" json:"WrappedKey,omitempty"`
	// Mechanism specific flags
	Flags                uint64   `protobuf:"varint,6,opt,name=Flags,proto3" json:"Flags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WrappingKeyInfo) Reset()         { *m = WrappingKeyInfo{} }
func (m *WrappingKeyInfo) String() string { return proto.CompactTextString(m) }
func (*WrappingKeyInfo) ProtoMessage()    {}
func (*WrappingKeyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *WrappingKeyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WrappingKeyInfo.Unmarshal(m, b)
}
func (m *WrappingKeyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WrappingKeyInfo.Marshal(b, m, deterministic)
}
func (m *WrappingKeyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WrappingKeyInfo.Merge(m, src)
}
func (m *WrappingKeyInfo) XXX_Size() int {
	return xxx_messageInfo_WrappingKeyInfo.Size(m)
}
func (m *WrappingKeyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_WrappingKeyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_WrappingKeyInfo proto.InternalMessageInfo

func (m *WrappingKeyInfo) GetMechanism() uint64 {
	if m != nil {
		return m.Mechanism
	}
	return 0
}

func (m *WrappingKeyInfo) GetHMACMechanism() uint64 {
	if m != nil {
		return m.HMACMechanism
	}
	return 0
}

func (m *WrappingKeyInfo) GetKeyID() string {
	if m != nil {
		return m.KeyID
	}
	return ""
}

func (m *WrappingKeyInfo) GetHMACKeyID() string {
	if m != nil {
		return m.HMACKeyID
	}
	return ""
}

func (m *WrappingKeyInfo) GetWrappedKey() []byte {
	if m != nil {
		return m.WrappedKey
	}
	return nil
}

func (m *WrappingKeyInfo) GetFlags() uint64 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func init() {
	proto.RegisterType((*EncryptedBlobInfo)(nil), "github.com.hashicorp.go.kms.wrapping.types.EncryptedBlobInfo")
	proto.RegisterType((*WrappingKeyInfo)(nil), "github.com.hashicorp.go.kms.wrapping.types.WrappingKeyInfo")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x3d, 0x4f, 0xfb, 0x30,
	0x10, 0xc6, 0xe5, 0xfc, 0xd3, 0xb7, 0x6b, 0xff, 0x20, 0x2c, 0x06, 0x0f, 0x08, 0x45, 0x15, 0x43,
	0xc4, 0xe0, 0x01, 0x46, 0x26, 0xca, 0x8b, 0x40, 0x55, 0x25, 0xe4, 0xa1, 0x95, 0x58, 0x90, 0x9b,
	0xba, 0xb1, 0xd5, 0x26, 0xb6, 0x12, 0xb7, 0x90, 0x4f, 0xc7, 0xc7, 0xe1, 0x6b, 0x20, 0x3b, 0x94,
	0x14, 0x26, 0xb6, 0x7b, 0x7e, 0xb9, 0xbb, 0xdc, 0xf3, 0x18, 0xfa, 0xb6, 0x32, 0xa2, 0xa4, 0xa6,
	0xd0, 0x56, 0xe3, 0xf3, 0x54, 0x59, 0xb9, 0x99, 0xd3, 0x44, 0x67, 0x54, 0xf2, 0x52, 0xaa, 0x44,
	0x17, 0x86, 0xa6, 0x9a, 0xae, 0xb2, 0x92, 0xbe, 0x16, 0xdc, 0x18, 0x95, 0xa7, 0xd4, 0x4f, 0x0c,
	0x3f, 0x10, 0x1c, 0xdd, 0xe5, 0x49, 0x51, 0x19, 0x2b, 0x16, 0xa3, 0xb5, 0x9e, 0x3f, 0xe6, 0x4b,
	0x8d, 0x4f, 0x01, 0x12, 0x65, 0xa4, 0x28, 0xac, 0x78, 0xb3, 0x04, 0x45, 0x28, 0x1e, 0xb0, 0x3d,
	0x82, 0x0f, 0x20, 0x50, 0x5b, 0x12, 0x78, 0x1e, 0xa8, 0x2d, 0xc6, 0x10, 0xca, 0x8c, 0x27, 0xe4,
	0x9f, 0x27, 0xbe, 0xc6, 0x04, 0x3a, 0xfe, 0x5f, 0x62, 0x41, 0xc2, 0x08, 0xc5, 0x5d, 0xb6, 0x93,
	0x78, 0x0a, 0xdd, 0x95, 0xa8, 0x5e, 0x54, 0xbe, 0xd4, 0xa4, 0x15, 0xa1, 0xb8, 0x7f, 0x71, 0x45,
	0xff, 0x7e, 0x32, 0x9d, 0x7d, 0xc9, 0xb1, 0xa8, 0xdc, 0xb1, 0xac, 0xb3, 0xaa, 0x0b, 0x7c, 0x02,
	0xbd, 0x29, 0x5f, 0x6f, 0xc4, 0x13, 0xb7, 0x92, 0xb4, 0x23, 0x14, 0xf7, 0x58, 0x03, 0x86, 0xef,
	0x08, 0x0e, 0x7f, 0x8d, 0xba, 0x89, 0x89, 0x48, 0x24, 0xcf, 0x55, 0x99, 0x79, 0x9b, 0x21, 0x6b,
	0x00, 0x3e, 0x83, 0xff, 0x0f, 0x93, 0xeb, 0x9b, 0xa6, 0x23, 0xf0, 0x1d, 0x3f, 0x21, 0x3e, 0x86,
	0x96, 0x5b, 0x77, 0xeb, 0xcd, 0xf7, 0x58, 0x2d, 0xdc, 0x66, 0xd7, 0x56, 0x7f, 0x09, 0xeb, 0x5b,
	0xbe, 0x81, 0xcb, 0x77, 0x56, 0x87, 0x31, 0x16, 0x95, 0xcf, 0x60, 0xc0, 0xf6, 0x88, 0xdb, 0x79,
	0xbf, 0xe6, 0x69, 0xe9, 0x5d, 0x84, 0xac, 0x16, 0x23, 0x78, 0xee, 0xee, 0xa2, 0x98, 0xb7, 0xfd,
	0x53, 0x5f, 0x7e, 0x06, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xe0, 0x8e, 0x70, 0xf9, 0x01, 0x00, 0x00,
}
