# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

# these services are required to be up before running the example.  after the
# vaul-server is up and running, the vault-client connects and initializes the
# required vault transit backend.   

version: "3.8"
services:
  vault-server:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
    cap_add:
      - IPC_LOCK

  vault-client:
    build: .
    environment:
      VAULT_ADDR: "http://vault-server:8200"
