// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package plugin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WrapClient is the client API for Wrap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WrapClient interface {
	PluginInfo(ctx context.Context, in *PluginInfoRequest, opts ...grpc.CallOption) (*PluginInfoResponse, error)
	Type(ctx context.Context, in *TypeRequest, opts ...grpc.CallOption) (*TypeResponse, error)
	KeyId(ctx context.Context, in *KeyIdRequest, opts ...grpc.CallOption) (*KeyIdResponse, error)
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error)
	Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error)
	Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error)
}

type wrapClient struct {
	cc grpc.ClientConnInterface
}

func NewWrapClient(cc grpc.ClientConnInterface) WrapClient {
	return &wrapClient{cc}
}

func (c *wrapClient) PluginInfo(ctx context.Context, in *PluginInfoRequest, opts ...grpc.CallOption) (*PluginInfoResponse, error) {
	out := new(PluginInfoResponse)
	err := c.cc.Invoke(ctx, "/github.com.hashicorp.go.kms.wrapping.plugin.v1.Wrap/PluginInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrapClient) Type(ctx context.Context, in *TypeRequest, opts ...grpc.CallOption) (*TypeResponse, error) {
	out := new(TypeResponse)
	err := c.cc.Invoke(ctx, "/github.com.hashicorp.go.kms.wrapping.plugin.v1.Wrap/Type", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrapClient) KeyId(ctx context.Context, in *KeyIdRequest, opts ...grpc.CallOption) (*KeyIdResponse, error) {
	out := new(KeyIdResponse)
	err := c.cc.Invoke(ctx, "/github.com.hashicorp.go.kms.wrapping.plugin.v1.Wrap/KeyId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrapClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error) {
	out := new(SetConfigResponse)
	err := c.cc.Invoke(ctx, "/github.com.hashicorp.go.kms.wrapping.plugin.v1.Wrap/SetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrapClient) Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error) {
	out := new(EncryptResponse)
	err := c.cc.Invoke(ctx, "/github.com.hashicorp.go.kms.wrapping.plugin.v1.Wrap/Encrypt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wrapClient) Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error) {
	out := new(DecryptResponse)
	err := c.cc.Invoke(ctx, "/github.com.hashicorp.go.kms.wrapping.plugin.v1.Wrap/Decrypt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WrapServer is the server API for Wrap service.
// All implementations must embed UnimplementedWrapServer
// for forward compatibility
type WrapServer interface {
	PluginInfo(context.Context, *PluginInfoRequest) (*PluginInfoResponse, error)
	Type(context.Context, *TypeRequest) (*TypeResponse, error)
	KeyId(context.Context, *KeyIdRequest) (*KeyIdResponse, error)
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error)
	Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error)
	Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error)
	mustEmbedUnimplementedWrapServer()
}

// UnimplementedWrapServer must be embedded to have forward compatible implementations.
type UnimplementedWrapServer struct {
}

func (UnimplementedWrapServer) PluginInfo(context.Context, *PluginInfoRequest) (*PluginInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PluginInfo not implemented")
}
func (UnimplementedWrapServer) Type(context.Context, *TypeRequest) (*TypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Type not implemented")
}
func (UnimplementedWrapServer) KeyId(context.Context, *KeyIdRequest) (*KeyIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeyId not implemented")
}
func (UnimplementedWrapServer) SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedWrapServer) Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Encrypt not implemented")
}
func (UnimplementedWrapServer) Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decrypt not implemented")
}
func (UnimplementedWrapServer) mustEmbedUnimplementedWrapServer() {}

// UnsafeWrapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WrapServer will
// result in compilation errors.
type UnsafeWrapServer interface {
	mustEmbedUnimplementedWrapServer()
}

func RegisterWrapServer(s grpc.ServiceRegistrar, srv WrapServer) {
	s.RegisterService(&Wrap_ServiceDesc, srv)
}

func _Wrap_PluginInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PluginInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WrapServer).PluginInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.hashicorp.go.kms.wrapping.plugin.v1.Wrap/PluginInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WrapServer).PluginInfo(ctx, req.(*PluginInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wrap_Type_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WrapServer).Type(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.hashicorp.go.kms.wrapping.plugin.v1.Wrap/Type",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WrapServer).Type(ctx, req.(*TypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wrap_KeyId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WrapServer).KeyId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.hashicorp.go.kms.wrapping.plugin.v1.Wrap/KeyId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WrapServer).KeyId(ctx, req.(*KeyIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wrap_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WrapServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.hashicorp.go.kms.wrapping.plugin.v1.Wrap/SetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WrapServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wrap_Encrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WrapServer).Encrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.hashicorp.go.kms.wrapping.plugin.v1.Wrap/Encrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WrapServer).Encrypt(ctx, req.(*EncryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wrap_Decrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WrapServer).Decrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.hashicorp.go.kms.wrapping.plugin.v1.Wrap/Decrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WrapServer).Decrypt(ctx, req.(*DecryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Wrap_ServiceDesc is the grpc.ServiceDesc for Wrap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Wrap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.hashicorp.go.kms.wrapping.plugin.v1.Wrap",
	HandlerType: (*WrapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PluginInfo",
			Handler:    _Wrap_PluginInfo_Handler,
		},
		{
			MethodName: "Type",
			Handler:    _Wrap_Type_Handler,
		},
		{
			MethodName: "KeyId",
			Handler:    _Wrap_KeyId_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _Wrap_SetConfig_Handler,
		},
		{
			MethodName: "Encrypt",
			Handler:    _Wrap_Encrypt_Handler,
		},
		{
			MethodName: "Decrypt",
			Handler:    _Wrap_Decrypt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/github.com.hashicorp.go.kms.wrapping.plugin.v1.proto",
}

// InitFinalizeClient is the client API for InitFinalize service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InitFinalizeClient interface {
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	Finalize(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (*FinalizeResponse, error)
}

type initFinalizeClient struct {
	cc grpc.ClientConnInterface
}

func NewInitFinalizeClient(cc grpc.ClientConnInterface) InitFinalizeClient {
	return &initFinalizeClient{cc}
}

func (c *initFinalizeClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, "/github.com.hashicorp.go.kms.wrapping.plugin.v1.InitFinalize/Init", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initFinalizeClient) Finalize(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (*FinalizeResponse, error) {
	out := new(FinalizeResponse)
	err := c.cc.Invoke(ctx, "/github.com.hashicorp.go.kms.wrapping.plugin.v1.InitFinalize/Finalize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InitFinalizeServer is the server API for InitFinalize service.
// All implementations must embed UnimplementedInitFinalizeServer
// for forward compatibility
type InitFinalizeServer interface {
	Init(context.Context, *InitRequest) (*InitResponse, error)
	Finalize(context.Context, *FinalizeRequest) (*FinalizeResponse, error)
	mustEmbedUnimplementedInitFinalizeServer()
}

// UnimplementedInitFinalizeServer must be embedded to have forward compatible implementations.
type UnimplementedInitFinalizeServer struct {
}

func (UnimplementedInitFinalizeServer) Init(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedInitFinalizeServer) Finalize(context.Context, *FinalizeRequest) (*FinalizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Finalize not implemented")
}
func (UnimplementedInitFinalizeServer) mustEmbedUnimplementedInitFinalizeServer() {}

// UnsafeInitFinalizeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InitFinalizeServer will
// result in compilation errors.
type UnsafeInitFinalizeServer interface {
	mustEmbedUnimplementedInitFinalizeServer()
}

func RegisterInitFinalizeServer(s grpc.ServiceRegistrar, srv InitFinalizeServer) {
	s.RegisterService(&InitFinalize_ServiceDesc, srv)
}

func _InitFinalize_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitFinalizeServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.hashicorp.go.kms.wrapping.plugin.v1.InitFinalize/Init",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitFinalizeServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitFinalize_Finalize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitFinalizeServer).Finalize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/github.com.hashicorp.go.kms.wrapping.plugin.v1.InitFinalize/Finalize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitFinalizeServer).Finalize(ctx, req.(*FinalizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InitFinalize_ServiceDesc is the grpc.ServiceDesc for InitFinalize service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InitFinalize_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "github.com.hashicorp.go.kms.wrapping.plugin.v1.InitFinalize",
	HandlerType: (*InitFinalizeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _InitFinalize_Init_Handler,
		},
		{
			MethodName: "Finalize",
			Handler:    _InitFinalize_Finalize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin/github.com.hashicorp.go.kms.wrapping.plugin.v1.proto",
}
