version: "3.8"

services:

  vault-server:
    image: vault:latest
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
    cap_add:
      - IPC_LOCK
    networks:
      vault-network:
        ipv4_address: 172.21.0.10
        aliases:
          - vault-server

  vault-client:
    build: .
    environment:
      VAULT_ADDR: "http://vault-server:8200"
    networks:
      vault-network:
        ipv4_address: 172.21.0.20
        aliases:
          - vault-client

networks:
  vault-network:
    ipam:
      config:
        - subnet: 172.21.0.0/24
