name: "make-gen-delta"
on:
  - workflow_dispatch
  - push
  - workflow_call

permissions:
  contents: read

jobs:
  make-gen-delta:
    name: "Check for uncommitted changes from make gen in extras/kms"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: '0'
      - name: Determine Go version
        id: get-go-version
        # We use .go-version as our source of truth for current Go
        # version, because "goenv" can react to it automatically.
        run: |
          echo "Building with Go $(cat .go-version)"
          echo "go-version=$(cat .go-version)" >> "$GITHUB_OUTPUT"
      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v.5.4.0
        with:
          go-version: "${{ steps.get-go-version.outputs.go-version }}"
      - name: Running go mod tidy
        run: |
          cd ./extras/kms
          go mod tidy
      - name: Install Dependencies
        run: |
          cd ./extras/kms
          make tools
      - name: Running make fmt
        run: |
          cd ./extras/kms
          make fmt
      - name: Check for changes
        run: |
          cd ./extras/kms
          git diff --exit-code
          git status --porcelain
          test -z "$(git status --porcelain)"
