name: Plugin-CLI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  plugin-cli:
    runs-on: ubuntu-22.04

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
        with:
          go-version: ${{ matrix.go }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: go mod package cache
        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go }}-${{ hashFiles('tests/go.mod') }}

      - name: Build
        run: find . -name go.mod -execdir sh -c 'pwd && CGO_ENABLED=0 go build ./... || exit 1' sh {} +

      - name: Run CLI
        run: |
          cd examples/plugin-cli
          ./plugin-cli
